### ISSUE TITLE
how can i use it ?

### ISSUE THREAD

**Issue by a7medo778** [ninachaubal/NIGameController#1]
hi there m8
i am a NOOB at the field of kinect

can you please help on how to use it ? what to download and what version of compability and how to run it

Best of regards
ahmed

**Comment by ninachaubal** [comment]
Sorry for the delay.

I was going to write a longish list of things you need but the nice people at SimpleOpenNi have put up a step by step installation guide at http://code.google.com/p/simple-openni/wiki/Installation
If you follow just the "Install OpenNI" part of the tutorial you should be able to run the NIGameController binaries (they are in Adapter/application.<windows/linux/macosx>)
If you want to play around with the code you can get processing at http://processing.org/download/ and follow the "Install SimpleOpenNI" part of the tutorial from the previous link.
We use SimpleOpenNI for all the gesture recognition stuff. 

for modifying the csv config files just make sure that the gesture name (the first field in each row) is the name of one of the classes from Adapter/Gesture.pde

**Comment by a7medo778** [comment]
thanks alot for the replay m8

i got openni and the middleware installed and have FAAST and other tools all running just fine

the files in the aplication folder ( .pde ) how can i run them ? within the openni it self or what ?

sorry if m question was too nooby by i just started poking around in the kinect area

**Comment by ninachaubal** [comment]
The .pde files are source code. You can open them in a text editor or
preferably in processing ( they are in the format processing uses) . If you
just want to run it there are executables under the application folders
(like the windows executable is inside application.windows) . If you have
all the openni stuff already the executable should run directly and give u a
window that let's you select the configuration file to use and then it will
start.

Niraj Chaubal
On Aug 31, 2011 8:42 PM, "a7medo778" <
reply@reply.github.com>
wrote:

**Comment by a7medo778** [comment]
sounds really good
so for each game you just got to create a new csv file
well done

i am having an issue that after i load the config file all i get is a black screen... nothing is recognized
and is there a list for the supported gestures ?

**Comment by ninachaubal** [comment]
Ya basically you just create a csv file mapping gestures to the keys your
game uses. If you open the gesture.pde file the class names in there are
valid gestures. So u can use
HandStretchForward
HandStretchOutward
SteerLeft
SteerRight
LeanForward
LeanBackward
LeanLeft
LeanRight
TwistLeft
TwistRight
SelfKnucklePunch
ForearmForward
ForearmBackward

See the csv files in the config folder they are for the games we demoed in
the video ( http://www.youtube.com/watch?v=Bq7mdl0yAy0 ) . Between them they
use all the gestures we have defined so far. Also see the config file for
portal to see how to activate the mouse.

Niraj Chaubal
On Aug 31, 2011 11:11 PM, "a7medo778" <
reply@reply.github.com>
wrote:

**Comment by a7medo778** [comment]
working perfectly :)
i know i must have bugged you already but 2 last questions
1- like the problem in FAAST , the hold the key action doesnt really work for emulators and other keybard input absed games
you can notice what i mean if you set an action to HOLD lets say the x key
when testing in notepad you will notice x is only pressed once... while when holding the button in the physical keyboard it keeps printing aslong as your holding it
so am i doing something wrong or what ( testing with virtualNES )

2- so to be able to add new gestures i should play around in the pde right ?

thanks again m8 :D

**Comment by ninachaubal** [comment]
Hold holds the key down as long as u continue to do the gesture. So if u had
some key, say w, on LeanForward with hold, you'd have to keep leaning
forward for it to keep leaning forward. With hit its like if u do the
gesture press and release the key, with hold its like if u do the gesture
press the key and release it when u stop doing the gesture. It should show
up repeatedly on notepad if it is hold and u continue doing the gesture. The
hold/hit are more on the lines of how does the game expect the key to be, do
u just press it, like enter in the menus or for switching weapons or do u
hold it like the accelerator key in a racing game.

To add more gestures u can define them in gesture.pde like the gestures that
are already there. Adapter.pde has some functions that do a lot of math with
the angles between the points on the body that the kinect picks up . They
are pretty convinient for defining gestures.

If u do add some new gestures send me a pull request on github so u can
contribute the new gestures back into the project. (And we will obviously
give u credit where its due)

Niraj Chaubal
On Aug 31, 2011 11:53 PM, "a7medo778" <
reply@reply.github.com>
wrote:
